### PR TITLE
Remove SCE

### LINKED ISSUE #113: Possible SCE check issue
Reference code:

https://github.com/klauspost/cpuid/blob/master/cpuid.go#L996

According to the _System V Application Binary Interface - AMD64 Architecture Processor Supplement_, section 3.1.1:

> Any program can expect that an AMD64 processor implements the baseline features mentioned in table 3.1. Most feature names correspond to CPUID bits, as described in the
> processor manual. Exceptions are OSFXSR and SCE, which are controlled by bits in the
> %cr4 register and the IA32_EFER MSR.

I understand that the presence of SCE must be checked using the MSR register

(You can generate the PDF mentioned above from https://gitlab.com/x86-psABIs/x86-64-ABI)

### PR DESCRIPTION
**Pull request by klauspost**
Remove SCE, since it was likely wrong.

Replaced by `SYSCALL` and `SYSEE` which are clearer. Use whichever you meant.

Fixes #113

### CODE REVIEW

File: cpuid.go [hunk 1]
```diff
@@ -190,6 +189,8 @@ const (
 	SVMNP                               // AMD SVM nested paging
 	SVMPF                               // SVM pause intercept filter. Indicates support for the pause intercept filter
 	SVMPFT                              // SVM PAUSE filter threshold. Indicates support for the PAUSE filter cycle count threshold
+	SYSCALL                             // SYSCALL and SYSRET instructions.
```
Comment (fpelliccioni) [inline cpuid.go:192]:
```suggestion
	SYSCALL                             // System-Call Extension (SCE): SYSCALL and SYSRET instructions.
```
